### ISSUE TITLE
NestJS Build Issue

### ISSUE THREAD

**Issue by Huseyinnurbaki** [taoqf/node-html-parser#120]
Hi,

Cannot use it with NestJS.

Steps to reproduce:

Create a nestjs project & install node-html-parse.

```console
nest start --debug --watch
```

Following error prompted 
---
```console
node_modules/node-html-parser/dist/nodes/comment.d.ts:17:17 - error TS1110: Type expected.

17     toString(): `<!--${string}-->`;
                   ~~~~~~~

node_modules/node-html-parser/dist/nodes/comment.d.ts:18:1 - error TS1128: Declaration or statement expected.

18 }
   ~

[1:08:35 AM] Found 2 errors. Watching for file changes.
```

Any typescript supported alternative ?

**Comment by Huseyinnurbaki** [comment]
found it, closing.

**Comment by iamswain25** [comment]
i came across the same error, what alternative did you find?

**Comment by boukeversteegh** [comment]
You could try to solve this by upgrading typescript.

This worked for me, in a vue 2.x project.

`package.json`

```diff
-   "typescript": "^3.9.9",
+   "typescript": "^4.3.5",
```

**Comment by nonara** [comment]
Interesting issue. Looks like the new TS is inferring template literals for return types. That's pretty wild! That's why it's failing with older TS. 

@Huseyinnurbaki I don't recommend keeping a separate fork, but you're welcome to. I'll create an issue and submit a PR which stops typescript from inferring template literals
