### ISSUE TITLE
Fix css-select import

### ISSUE THREAD

**Issue by rondonjon** [taoqf/node-html-parser#167]
May I suggest to change the `css-select` import in `html.ts` from

```
import { selectAll, selectOne } from 'css-select';

...

return selectAll( ...
```

to

```
import * as cssSelect from 'css-select';

...

return cssSelect.selectAll( ...
```

?

It seems that `css-select` is only exporting a CommonJS build, in which case the bundler/compiler must decide how to resolve the import.  At least for Snowpack (and possibly Rollup, which Snowpack uses internally) this seems to cause problems.

Bundlers [which follow the ESM specification strictly](https://www.typescriptlang.org/tsconfig#esModuleInterop) will resolve the `import` statement in the first snippet (version 5.0.0) to the default export of the CommonJS module, which is in this case the `selectAll` function of the `css-select` module. `{ selectAll, selectOne }` are then handled as a destructuring assignment on the expected object, i.e. they will refer to `selectAll.selectAll` and `selectAll.selectOne` and resolve to `undefined`. This doesn't cause immediate problems, but will raise runtime errors when the functions are invoked later in the code.

The second snippet / suggested change refers explicitly to the "exported namespace" of the CommonJS module, so that `selectAll` and `selectOne` will resolve to the named exports (the functions) as intended.

**Comment by henryholtgeerts** [comment]
Hello! I know this issue was closed -- but I'm running into the same problem @rondonjon described, when using the [plugin-node-resolve](https://github.com/rollup/plugins/tree/master/packages/node-resolve/#readme) plugin for Rollup. It apparently uses the [Node resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together) to sort out dependencies and seems to have the exact same problem with css-select import as was raised in this issue. Curious if you've got any insight here, or specific concern about rewriting the commonJS imports.
