### ISSUE TITLE
rawAttributes behaviour change?

### ISSUE THREAD

**Issue by minas90** [taoqf/node-html-parser#18]
On v1.2.0 rawAttributes returns values wrapped in `"`
Also what is the reason for not encoding entities in `setAttribute` anymore?

**Comment by taoqf** [comment]
Yes, @minas90 , because of this: https://github.com/taoqf/node-html-parser/issues/17 , That's why I raise the version to `1.2`
May getter `attributes` would do?
I did see any reason to encode value in `setAttribute`, I've done some tests in chrome. 
```js
const div = document.createElement('div');
// undefined
div.setAttribute('a', '&<>')
// undefined
div
// <div a=​"&<>">​</div>​
div.getAttribute('a')
// "&<>"
```

Do you think we should encode the value? Please show me some clue.

**Comment by minas90** [comment]
I see, `attributes` is like ~50% slower for my usecase, because it does the decoding.
I will do some testing on chrome to understand when it does decode / encode, if at all.

**Comment by minas90** [comment]
Yes, you are right, `setAttribute ` doesn't encode the value in browsers.
I [fixed](https://github.com/taoqf/node-html-parser/pull/19) the issue in this change.

**Comment by minas90** [comment]
I fixed some issues and tweaked some tests to match the behaviour of browsers. Now it's passing all the tests!
I also added `getAttribute`, so it's the same as in Chrome now.

Please review the changes and merge it.
