### ISSUE TITLE
Option to keep location info

### ISSUE THREAD

**Issue by stalniy** [taoqf/node-html-parser#25]
I want to use this parser in order to create rollup plugin and I need location info of some tags in order to correctly generate sourcemap for browser.

**Comment by taoqf** [comment]
Sorry for that, I don't know much about rollup, even I do not use sourcemap personally, but if you wish, pr is welcomed.

**Comment by stalniy** [comment]
The only thing which you need to do is to preserve information (index in original string) where each tag starts and ends. Additionally it is useful to safe info about line number and column number as well.

**Comment by stalniy** [comment]
I’ll try to implement it some day but for now I decided to use parse5 sax parser which has this info.

**Comment by ZitRos** [comment]
+1 for this improvement.

My use-case for having an original tag/etc position info (opening and closing tag): I need to find and replace specific `<script>` tags in the HTML, while **everything else** except the possibly found script **must** stay as it was before (i.e. whitespaces, comments, wrong HTML, something which this parser doesn't yet support, etc). Thus, I prefer to use HTML parser for finding scripts only (because it's not possibly to find them reliably with RegExp), and then replace those scripts with something else but in the original html string, using positions.

Thanks for the good library!

**Comment by nonara** [comment]
This feature has been added as of v4.1.0. Position information is accessible via `range` property on nodes
