### ISSUE TITLE
Comment parsing doesn't seem to work

### ISSUE THREAD

**Issue by ktrieu** [taoqf/node-html-parser#270]
I'm on Node v21.5.0 and version 6.1.12 of the library. I have a pretty simple test case that I believe should work, judging from the issue about adding comment support to `querySelector` (https://github.com/taoqf/node-html-parser/issues/221).

`index.js`
```
import { parse } from 'node-html-parser'
import * as fs from 'fs';

const html = fs.readFileSync('./test.html').toString();

const parsed = parse(html, { comment: true });

const comments = parsed.querySelectorAll('!--');

console.log(comments);
```

`test.html`
```
<html>
  <body>
    <h1>TEST</h1>
    <!-- Some comment here. -->
  </body>
</html>
```
However, running this code prints `[]`. I get the same result when the HTML is included inline as a raw string, so I don't think the file handling is at fault.

**Comment by alabsi91** [comment]
I can use `querySelector("!--")` to select a single comment node, but the issue still happens with `querySelectorAll("!--")`, which returns an empty array. I think the problem is in [this part of the code the `findAll` matcher](https://github.com/taoqf/node-html-parser/blob/d2b69e2a51ae112c215e83cdf707ea17a1da9f0f/src/matcher.ts#L98), `if (!isTag(nodes[i])) continue;` where the comment node is not treated as a tag.
