### ISSUE TITLE
support for xmlns:xlink

### ISSUE THREAD

**Issue by sayjeyhi** [taoqf/node-html-parser#42]
the `xmlns:xlink` will convert to `xmlns xlink` when we call `toString()`

**Comment by taoqf** [comment]
Sorry, I am a little busy recently, pr is welcomed.

**Comment by Schizhats** [comment]
Hello

Thank you for this library, it helped me a lot in one of my projects. 
However I had problems with the attributes when reading a SVG, I had "xmlns" & "xmlns:xlink" attributes, the problem is that the "rawAttributes" doesn't take into account these attributes. 

I don't know how I should proceed to fix a bug with your library. So I made a fork.

If you want to have the resolution of the problem here is my public git. (https://github.com/Wanderer-Guy/node-html-svg-parser)

The error was in the regex of "rawAttributes" here is the regex that solved my problem: /\b([a-z][a-z0-9-_:]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))))?/ig; (src/nodes/html.ts)
I also added tests to "#rawAttributes" in (test/html.js)

**Comment by taoqf** [comment]
@Schizhats Thanks.  v3.1.5 is released.
